### ISSUE TITLE
When { centered: true } onOverlayClicked function is not wroking.

### ISSUE THREAD

**Issue by rommelmamedov** [Upmostly/modali#40]

**Comment by Windynik** [comment]
Can confirm, this is a bug.

**Comment by iltimasd** [comment]
To those who stumble on this bug, until @lexcode gets their PR merged you can add this to your global CSS to make all modals centered and retain onOverlayClicked functionality

```css
.modali-wrapper {
  top: 0 !important;
  display: flex !important;
  align-items: center;
}
```
